/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hellojni_JavaNativeBridge */

#ifndef _Included_com_example_hellojni_JavaNativeBridge
#define _Included_com_example_hellojni_JavaNativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hellojni_JavaNativeBridge
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_sapindus_JavaNativeBridge_stringFromJNI
  (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_com_example_sapindus_JavaNativeBridge_timeFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
